spring:
  datasource:
    url: jdbc:postgresql://172.17.225.240:5432/postgres
    username: postgres
    password: Qazwsxedc1@
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true

logging:
  level:
    root: INFO
  file:
    name: service/pharma.log
    path: /