spring:
  datasource:
    url: jdbc:postgresql://172.17.225.240:5432/postgres
    username: postgres
    password: Qazwsxedc1@
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    default-schema: public

logging:
  level:
    org.springframework.jdbc.core: TRACE
  file:
    name: service/pharma.log
    path: /

app:
  image:
    bucket: "C:/Users/di.ma/IdeaProjects/_dmdev/dmdev-di-ma-hw1-maven/images"

